

on: 
 push:
   branches:
     - master  
jobs:
 build:
    runs-on: ubuntu-latest 
    steps:  
      - uses: actions/checkout@v3
      - name: 'Login in dockerhup'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
      - name: "build image"
        run: docker build -t ${{ secrets.USERNAME }}/image1 .
      - name: "push image"
        run: docker push ${{ secrets.USERNAME }}/image1